# This file was generated by GoReleaser. DO NOT EDIT.
cask "hop" do
  name "hop"
  desc "Fast, elegant SSH connection manager"
  homepage "https://github.com/danmartuszewski/hop"
  version "1.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hop"

  on_macos do
    on_intel do
      url "https://github.com/danmartuszewski/hop/releases/download/v#{version}/hop_darwin_amd64.tar.gz"
      sha256 "5b986aa28bc824296361e8f75ee95e9893a1b9071b7e0e397122f2b9498d0b7f"
    end
    on_arm do
      url "https://github.com/danmartuszewski/hop/releases/download/v#{version}/hop_darwin_arm64.tar.gz"
      sha256 "86ac9a76e5706150cc477c7182a7bf03df404563276748b8930a8c90e85a5ba3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danmartuszewski/hop/releases/download/v#{version}/hop_linux_amd64.tar.gz"
      sha256 "b912ac8b8dce8d3a6f1c79b8cfc3c99e947b154814142b0b29f31c6784b7a991"
    end
    on_arm do
      url "https://github.com/danmartuszewski/hop/releases/download/v#{version}/hop_linux_arm64.tar.gz"
      sha256 "60bdb85ec3ebe4a4776c08ebec91637bca9dedce3176e3b4bf45520bae4d6b2e"
    end
  end

  # No zap stanza required
end
