# This file was generated by GoReleaser. DO NOT EDIT.
cask "hop" do
  version "1.8.0"

  on_macos do
    on_intel do
      sha256 "d18cae2427b4eb328c7c9826b554948e3322cbc173db5a51cf1748a99b9dc6c0"
      url "https://github.com/danmartuszewski/hop/releases/download/v#{version}/hop_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3ae390b5c8c54ed4d8b5fcc0fb78ebc9a5b1053eb493f15f1932025bcb665d42"
      url "https://github.com/danmartuszewski/hop/releases/download/v#{version}/hop_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e5f3f5449a7c7dc012930e460d9b321e109912d497d9864a5060bc9a37d74e97"
      url "https://github.com/danmartuszewski/hop/releases/download/v#{version}/hop_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "162d248583062d1a116c1dd1941b47433f98f9a8b1fe5c88f3ea91af2ab4b103"
      url "https://github.com/danmartuszewski/hop/releases/download/v#{version}/hop_linux_arm64.tar.gz"
    end
  end

  name "hop"
  desc "Fast, elegant SSH connection manager"
  homepage "https://github.com/danmartuszewski/hop"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hop"

  # No zap stanza required

end
