# This file was generated by GoReleaser. DO NOT EDIT.
cask "hop" do
  name "hop"
  desc "Fast, elegant SSH connection manager"
  homepage "https://github.com/danmartuszewski/hop"
  version "1.0.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hop"

  on_macos do
    on_intel do
      url "https://github.com/danmartuszewski/hop/releases/download/v#{version}/hop_darwin_amd64.tar.gz"
      sha256 "8e780331f52ee630024b46795b5cee6cea93b331f30777eadfbb3ca32f667540"
    end
    on_arm do
      url "https://github.com/danmartuszewski/hop/releases/download/v#{version}/hop_darwin_arm64.tar.gz"
      sha256 "3314acc55ac6cffae8f49642db88adc94d99cb6fac9df169d5e1953e9a3a3c55"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/danmartuszewski/hop/releases/download/v#{version}/hop_linux_amd64.tar.gz"
      sha256 "b172a49cc2c8495a85bd0628cc1bcd236fe3715de173091e490bfe2aaa678e97"
    end
    on_arm do
      url "https://github.com/danmartuszewski/hop/releases/download/v#{version}/hop_linux_arm64.tar.gz"
      sha256 "7f11aba0978a42435ebaf29a634b5dbce322cdb31e2677e39886a43919fa8e29"
    end
  end

  # No zap stanza required
end
