# Generated by the Tabnax release workflow. Do not edit.
cask "tabnax" do
  version "0.1.0"
  sha256 "59494897cbacf6cb2a332efa8a5897846d51b1f5315cf58e68a5af8b0bc28ef7"

  url "https://github.com/danmartuszewski/tabnax/releases/download/v#{version}/Tabnax-#{version}.dmg"
  name "Tabnax"
  desc "Keyboard-driven switcher for windows, browser tabs and apps"
  homepage "https://github.com/danmartuszewski/tabnax"

  livecheck do
    url :url
    strategy :github_latest
  end

  auto_updates true
  depends_on arch: :arm64
  depends_on macos: ">= :sequoia"

  app "Tabnax.app"

  # Not notarized by Apple: clear the download quarantine so macOS opens the app.
  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{appdir}/Tabnax.app"]
  end

  uninstall quit: "pl.tabnax.Tabnax"

  zap trash: [
    "~/Library/Application Support/Mozilla/NativeMessagingHosts/pl.tabnax.bridge.json",
    "~/Library/Application Support/zen/NativeMessagingHosts/pl.tabnax.bridge.json",
    "~/Library/Caches/pl.tabnax.Tabnax",
    "~/Library/Containers/pl.tabnax.Tabnax.Safari",
    "~/Library/HTTPStorages/pl.tabnax.Tabnax",
    "~/Library/Preferences/pl.tabnax.Tabnax.plist",
  ]

  caveats <<~EOS
    Tabnax is signed with the project's own certificate, not notarized by Apple.
    The cask clears the download quarantine so the app opens normally.
  EOS
end
